web:
   image: tutum/apache-php
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "80:80"
   links:
     - db
   volumes:
     - ./app:/app

db:
  image: postgres:9.4
  ports:
    - "15000:5432"
  env_file: .env
  volumes:
    - ./data:/docker-entrypoint-initdb.d
